apiVersion: v1
kind: Service
metadata:
  name: nginxserver-sample-service
spec:
  selector:
    app: nginxserver-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
